baseURL = "https://demo-hugo.pages.dev/"
languageCode = "en-us"
title = "Hugo Demo"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Hugo"
  description = "Demo Site"
  github = "hugodemo"
  facebook = "hugodemo"
  twitter = "hugodemo"
  linkedin = "hugodemo"
  instagram = "hugodemo"
  tumblr = "hugodemo"
  email = "info@demo-hugo.pages.dev"
  url = "https://demo-hugo.pages.dev"
  keywords = "code"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Demoland"

  [[params.links]]
    title = "Code"
    href = "https://github.com/sjaconsulting/demo-hugo"
  [[params.links]]
    title = "Website"
    href = "https://demo-hugo.pages.dev"
    icon = "/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]